version: "3.3"

services:

  jenkins:
    image: virussauron/jenkins-docker:latest
    build: .
    ports:
      - 7100:7100
    volumes:
    - jenkins_data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://192.168.1.88:2375
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.has_persistence==true"

volumes:
  jenkins_data:
