version: "3.3"

services:

  jenkins:
    image: virussauron/jenkins-docker:latest
    build: .
    ports:
      - 7100:7100
    volumes:
    - jenkins_data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://192.168.1.32:2375
    deploy:
      replicas: 1

volumes:
  jenkins_data:
    driver_opts:
      type: "nfs"
      o: "addr=ss.sauron.ai,nolock,soft,rw"
      device: ":/storage/projects/ci/jenkins_home"
