version: "3.3"

services:

  jenkins:
    image: aminebouamama/jenkins-docker:latest
    build: .
    ports:
      - 7100:8080
    volumes:
    - jenkins_data:/var/jenkins_home
    deploy:
      replicas: 1

volumes:
  jenkins_data:
